name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit-tests-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache-dependency-path: bugtracker-backend/go.sum

      - name: Execute Backend Unit tests
        working-directory: ./bugtracker-backend
        run: |
          go test -v ./...

  unit-tests-frontend:
    needs: unit-tests-backend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Update npm to latest version
        run: npm install -g npm@latest

      - name: Remove lockfile and node_modules
        working-directory: ./bugtracker-frontend
        run: |
          rm -rf node_modules package-lock.json

      - name: Clean install dependencies
        working-directory: ./bugtracker-frontend
        run: npm install

      - name: Execute Frontend Unit Tests (serial mode for clarity)
        working-directory: ./bugtracker-frontend
        run: npm test -- --runInBand

      - name: Publish Frontend Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Frontend Unit Tests Report
          path: bugtracker-frontend/test-results.xml
          reporter: jest-junit
